version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-24-ndk

    working_directory: ~

    environment:
      MIN_SDK_VERSION: 21
      HOST_TAG: linux-x86_64

    steps:
      - checkout

      - run: git submodule update --init --recursive

      - run: sudo sh -c "apt update && apt install autoconf libtool"

      - run: chmod +x ./build.sh && ./build.sh

      - run: tar cvzf curl.tar.gz build

      - store_artifacts:
          path: curl.tar.gz

      - run: echo "$(git -C curl describe --abbrev=0)"_"$(git -C openssl describe --abbrev=0)" > VERSION

      - persist_to_workspace:
          root: .
          paths:
            - curl.tar.gz
            - VERSION



  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/VERSION)
            mv ./artifacts/curl.tar.gz ./artifacts/${VERSION}.tar.gz
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/${VERSION}.tar.gz

workflows:
  version: 2
  build-and-publish-release:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
            

